module_name: Block CMS
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - cms pages
  - cms
  - cms links
short_description: The block CMS module allows you to add links to your cms pages in the left or right column of your shop.
description: description.md
images:
  - image-1.png
  - image-2.png
license: MIT